import type { Metadata } from "next";
import Nav from "@/components/Nav";
import NewsletterFooter from "@/components/NewsletterFooter";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Disclaimer — martin.builds",
  description: "Disclaimer for martin.builds. Results vary. Content is for informational purposes.",
};

const sectionStyle: React.CSSProperties = { marginBottom: "2.5rem" };
const h2Style: React.CSSProperties = { fontSize: "1.3rem", fontWeight: 700, marginBottom: "0.75rem", color: "#f5f5f0" };
const pStyle: React.CSSProperties = { fontSize: "1rem", lineHeight: 1.8, color: "#ccc", marginBottom: "1rem" };

export default function DisclaimerPage() {
  return (
    <>
      <Nav />
      <main style={{ minHeight: "100vh", padding: "clamp(6rem,12vw,8rem) clamp(1.25rem,5vw,3rem) 4rem" }}>
        <div style={{ maxWidth: 750, margin: "0 auto" }}>
          <div style={{ fontFamily: "'Space Mono', monospace", fontSize: "0.8rem", color: "#c8ff00", letterSpacing: "3px", textTransform: "uppercase", marginBottom: "1rem" }}>
            LEGAL
          </div>
          <h1 style={{ fontSize: "clamp(2.5rem, 6vw, 4rem)", fontWeight: 900, letterSpacing: "-2px", marginBottom: "1rem" }}>
            Disclaimer
          </h1>
          <p style={{ fontSize: "0.85rem", color: "#888", marginBottom: "3rem" }}>Last updated: March 2026</p>

          <div style={sectionStyle}>
            <h2 style={h2Style}>General</h2>
            <p style={pStyle}>
              The information and services provided by martin.builds are offered on an as-is basis. While we work hard to deliver quality results, we make no warranties or guarantees regarding specific outcomes, revenue increases, or business results from our work.
            </p>
          </div>

          <div style={sectionStyle}>
            <h2 style={h2Style}>Not Professional Advice</h2>
            <p style={pStyle}>
              Nothing on this site constitutes legal, financial, or professional advice. Our services are focused on building AI tools and web applications. For legal, tax, or compliance matters, consult a qualified professional.
            </p>
          </div>

          <div style={sectionStyle}>
            <h2 style={h2Style}>Third-Party Links</h2>
            <p style={pStyle}>
              This site may contain links to third-party websites or services. We are not responsible for the content, privacy practices, or availability of those external sites.
            </p>
          </div>

          <div style={sectionStyle}>
            <h2 style={h2Style}>AI-Generated Content</h2>
            <p style={pStyle}>
              Some content or outputs from our AI agent services are generated by artificial intelligence. AI-generated content may contain errors or inaccuracies. It should be reviewed before being relied upon for business decisions.
            </p>
          </div>

          <div style={sectionStyle}>
            <h2 style={h2Style}>Contact</h2>
            <p style={pStyle}>
              Questions or concerns? Use the contact form at <a href="/contact" style={{ color: "#c8ff00", textDecoration: "none" }}>/contact</a>.
            </p>
          </div>
        </div>
      </main>
      <NewsletterFooter />
      <Footer />
    </>
  );
}
